### ISSUE TITLE
.vimrc ctrl-p plugin

### ISSUE THREAD

**Issue by jomuller** [MaximeWack/dotfiles#1]
I didn't saw the very useful [Ctrl-P](https://github.com/kien/ctrlp.vim) vim plugin in your `.vimrc`. Do you use it? It's without any doubt my favorite plugin.

**Comment by MaximeWack** [comment]
Je l'ai inclus ya pas longtemps, mais j'ai pas encore commit ou push la
modification, il faut que je le configure parce que là il ne m'est pas
très utile, par exemple si je lui demande simplement le .vimrc il me
sort une tonne de fichiers qui n'ont rien à voir…

**Comment by MaximeWack** [comment]
I don't use CtrlP anymore but FZF. It also comes with a command-line and zsh plugin for fuzzy file matching! You should try it!

**Comment by MaximeWack** [comment]
In fact neither CtrlP nor FZF are needed because vim understands deep path globbing with \*\*.
For example `:args **/*.R` will open all the R files in all the subdirectories from the current location.
